

web: bench serve  --port 8000


socketio: /Users/vijayrasquinha/.nvm/versions/node/v22.12.0/bin/node apps/frappe/socketio.js


watch: bench watch


schedule: bench schedule

worker: OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES NO_PROXY=* bench worker 1>> logs/worker.log 2>> logs/worker.error.log

